apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam-website-deployment
  labels:
    app: sam-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sam-website
  template:
    metadata:
      labels:
        app: sam-website
    spec:
      containers:
      - name: sam-website
        image: sama863nz/sam-website
        ports:
        - containerPort: 80
