apiVersion: v1
kind: Service
metadata:
  name: sam-website-service
  labels:
    app: sam-website
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: sam-website
